//! Centralized ingress/egress size caps (EP-003, US-013).
//!
//! Every bound that protects an allocation, a parse, or a spawn from untrusted
//! or hand-edited input is gathered here so a read cap and its matching write
//! cap stay in sync - the "validate on both directions" invariant can't
//! silently rot when the two numbers live a screen apart in different files.
//!
//! Three caps are owned by the module/crate that defines their domain and are
//! cross-referenced here:
//!
//! - **`MAX_PANES`** (32) - [`crate::layout::MAX_PANES`]. Live UI create cap
//!   (split / drop-to-split / IPC `surface.split` / `workspace.create`) ↔ read
//!   cap in [`paneflow_config::schema::validate_layout`] (US-011) and at session
//!   restore (US-009). Since US-001 of `prd-cli-tab-hierarchy` it bounds a
//!   *tab*, not a workspace: every create site counts the targeted tab's
//!   leaves, and a workspace's total pane count is the sum over its tabs.
//! - **`MAX_WORKSPACES`** (20) - [`crate::workspace::MAX_WORKSPACES`]. Live
//!   `workspace.create` cap ↔ `restore_workspaces` cap (US-009).
//! - **`MAX_TABS_PER_WORKSPACE`** (32) -
//!   [`crate::workspace::MAX_TABS_PER_WORKSPACE`]. Live tab create cap
//!   (US-001, `prd-cli-tab-hierarchy`), declared next to `MAX_WORKSPACES`.
//!   Read-cap half: `restore_workspaces` truncates a session's tab list, and
//!   [`paneflow_config::schema::MAX_SESSION_TABS`] applies the same bound to
//!   the v1 -> v2 migration (US-018), whose surplus is logged, not silent.
//! - **`MAX_CONFIG_SIZE_BYTES`** (1 MiB) - `paneflow_config::loader`. Read cap
//!   on `paneflow.json`; the app's own config writer never approaches it.

/// Per-line read cap on untrusted agent-written session JSONL
/// (`claude_sessions`, `codex_sessions`). The agents are the (external) write
/// side; a line over this is treated as malformed and the file is skipped.
/// Deduplicated from two identical `const`s (US-013).
pub(crate) const MAX_LINE_BYTES: u64 = 64 * 1024;

/// Cap on an OSC52 clipboard payload, applied on BOTH the Store (write) and
/// Load (read) paths in the terminal. Deduplicated from two identical `const`s
/// (US-013); keeping one source is what guarantees Store and Load stay
/// symmetric (EP-004 US-015).
pub(crate) const MAX_OSC52_BYTES: usize = 100 * 1024;

/// JSON-RPC framing ceiling on the local IPC socket: the server's per-line read
/// (`read_capped_line` in `ipc.rs`) and every shared IPC client use this one
/// cross-crate value for requests, replies, and AI-hook notifications.
pub(crate) const MAX_REQUEST_LEN: u64 = paneflow_ipc_client::MAX_FRAME_BYTES as u64;

/// Maximum body text returned by `surface.read` before JSON envelope overhead
/// and optional untrusted-output fencing. Kept below [`MAX_REQUEST_LEN`] so a
/// legitimate read response cannot exceed the client-side 256 KiB frame cap.
pub(crate) const MAX_IPC_TEXT_BYTES: usize = 240 * 1024;

/// Read cap on `session.json` (U-008/U-016). Sized from the write side: the
/// engine's own 4000-line scrollback cap per pane × `MAX_PANES` ×
/// `MAX_WORKSPACES` is a few hundred MB
/// worst-case, but a realistic maxed session is a few MB - 64 MiB sits far
/// above any legitimate session while bounding a multi-hundred-MB tampered file
/// before it is read whole into RAM. Mirrors `MAX_CONFIG_SIZE_BYTES` for
/// `paneflow.json`, which previously had no session-side counterpart.
pub(crate) const MAX_SESSION_SIZE_BYTES: u64 = 64 * 1024 * 1024;

/// Read cap on the markdown scroll-position cache. This file is generated by
/// Paneflow but lives in a user-writable cache directory, so a corrupt or
/// maliciously oversized local file must not be read whole before JSON parse.
pub(crate) const MAX_MARKDOWN_STATE_SIZE_BYTES: u64 = 1024 * 1024;
