blink_heap_inside_shared_library=true
blink_symbol_level=0
chrome_pgo_phase=0
clang_use_chrome_plugins=false
dcheck_always_on=true
enable_background_mode=false
enable_downgrade_processing=false
enable_linux_installer=false
enable_precompiled_headers=false
enable_resource_allowlist_generation=false
enable_widevine=true
forbid_non_component_debug_builds=false
is_cfi=false
is_component_build=false
is_debug=false
optimize_webui=true
symbol_level=0
target_cpu="x64"
use_qt5=false
use_qt6=false
use_remoteexec=false
use_siso=false
use_sysroot=true
use_thin_lto=false
v8_symbol_level=0
root_extra_deps = [ "//paneflow_tsync_probe:paneflow_tsync_probe" ]
